### ISSUE TITLE
https://koreantutorials.github.io/PythonTutorial/ 사이트의 행방

### ISSUE THREAD

**Issue by sunrabbit123** [KoreanTutorials/PythonTutorial#21]
#16  에서 제안을 받아 #20  에서 기여를 받게 된 사이트의 링크가 노출되지않습니다.
이로 인해 접근성이 많이 떨어지는 것 같습니다.

[https://github.com/KoreanTutorials/PythonTutorial](https://github.com/KoreanTutorials/PythonTutorial)에서 오른쪽 측면에 있는 About에 페이지를 기입하는 것은 어떨까요?

**Comment by Lapis0875** [comment]
추가해두겠습니다!
